### ISSUE TITLE
bug when ndims == 3?

### ISSUE THREAD

**Issue by brodyh** [spillai/numpy-opencv-converter#1]
Hi Sudeep,

Is it safe to uncomment the code [here](https://github.com/spillai/numpy-opencv-converter/blob/master/utils/conversion.cpp#L262) for conversions from 3 dimensional numpy arrays? I needed it for converting RGB images to cv::Mat. 

Thanks!

**Comment by spillai** [comment]
Yes, it's safe. Just make sure the size() is consistent with rows/cols. I recall it wasn't when I had it uncommented earlier. I'll try to fix it over the weekend, but meanwhile just uncomment and check the values of  mat.size() and mat.rows/mat.cols before you access them.

**Comment by sromberg** [comment]
Do you a have a newer version that supports matrices with 3 channels such as color images?
