### ISSUE TITLE
Git Clone failing

### ISSUE THREAD

**Issue by tinashemudavanhu** [spillai/numpy-opencv-converter#5]
root@beaglebone:~# git clone git@github.com:spillai/numpy-opencv-converter
Cloning into 'numpy-opencv-converter'...
Warning: Permanently added the RSA host key for IP address '192.30.252.123' to the list of known hosts.
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by spillai** [comment]
This isn't related to the repo, but this [link](https://help.github.com/articles/error-permission-denied-publickey/) should help. I suspect its a sudo / super-user privilege issue.
